"""NSFW intensity presets for Stable Waifu prompts.

Edit this file if you want to provide your own NSFW tags. Keep each level compact
and coherent; the prompt builder appends all levels up to STABLE_WAIFU_NSFW_LEVEL.
"""

NSFW_LEVELS = {
    0: [],
    1: [
        "adult woman",
        "transparent dress",
        "lingerie",
        "naked ribbon",
        "skirt lift",
        "panties",
        "garter straps",
        "bikini",
        "condom belt",
        "ass focus",
        "licking lips",
        "parted lips",
        "presenting",
    ],
    2: [
        "nude",
        "naked body",
        "completely naked",
        "completely nude",
        "breasts",
        "huge breast",
        "nipples",
        "ass",
        "pussy",
        "penis",
        "dick",
        "sex toy",
        "anal beads",
        "spread anus",
        "ahegao",
    ],
    3: [
        "sex",
        "cum",
        "cumshot",
        "huge cumshot",
        "cum on stomach",
        "cum on face",
        "cum on body",
        "cum in pussy",
        "cum in ass",
        "excessive cum",
        "facial",
        "ejaculation",
        "fellatio",
        "sucks dick",
        "footjob",
        "fingering",
        "fingering other",
        "vaginal",
        "anal",
        "paizuri",
        "cooperative paizuri",
        "tribadism",
        "yuri",
        "doggystyle",
        "cowgirl position",
        "spanking the ass",
        "grabbing another's breast",
        "breasts squeezed together",
    ],
    4: [
        "group sex",
        "orgy",
        "hetero",
        "multiple girls",
        "multiple boys",
        "strap-on",
        "male penetrated",
        "tentacle sex",
        "tentacle in pussy",
        "milking machine",
        "x-ray",
    ],
}
